export const routes = {
  getAllPricing: () => "/api/home/subcription/all",
  getTrunkUserInfo: () => "/api/company/Trunk",
  getActiveSubInfo: () => "/api/membership/UserCurrentActiveSub",
  getUserInfo: () => "/api/company/GetUsers",
  registerUser: () => "/api/user/register",
  loginUser: () => "/api/user/login",
  confirmUser: () => "/api/user/confirm_email",
  dashboardGraphUrl: () => "/api/page/GetDashboardGraph",
  mostContact: () => "/api/company/GetMostContacted",
  extensionUrl: () => "/api/company/CompanyUserDetail/",
  windowDownloadUrl: () => "/api/home/DownloadWindows/",
  debisnDownloadUrl: () => "/api/home/DownloadDebian/",
  forgetPassword: () => "/api/user/ForgotPassword",
};
